version: '3.8'

services:
  frontend:
    build: .
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - proxy
    expose:
      - "80"

networks:
  proxy:
    external: true
    name: docker-reverse-proxy_proxy
