name: SolidJS Frontend Deployment

on:
  push:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Determine Deploy Environment
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          if [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
            echo "ENV_FILE=.env.prod" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "development" ]]; then
            echo "ENV_FILE=.env.dev" >> $GITHUB_ENV
          else
            echo "Invalid environment input: ${{ github.event.inputs.environment }}"
            exit 1
          fi
        else
          BRANCH="${GITHUB_REF##*/}"
          if [[ "$BRANCH" == "main" ]]; then
            echo "ENV_FILE=.env.prod" >> $GITHUB_ENV
          elif [[ "$BRANCH" == "dev" ]]; then
            echo "ENV_FILE=.env.dev" >> $GITHUB_ENV
          else
            echo "Unsupported branch for deployment: $BRANCH"
            exit 1
          fi
        fi

    - name: Deploy with Docker Compose
      run: |
        docker compose --env-file $ENV_FILE down
        docker compose --env-file $ENV_FILE build
        docker compose --env-file $ENV_FILE up -d
