name: SolidJS Frontend Deployment

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  build-and-deploy:
    name: Build and Deploy SolidJS Frontend App
    runs-on: self-hosted
    
    env:
      DEPLOY_PATH: >-
        ${{
          (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production') && '/var/www/your-domain.com/html/' ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'development') && '/var/www/dev.your-domain.com/html/' ||
          (github.ref == 'refs/heads/main') && '/var/www/your-domain.com/html/' ||
          '/var/www/dev.your-domain.com/html/'
        }}
      ENV_NAME: >-
        ${{
          (github.event_name == 'workflow_dispatch') && github.event.inputs.environment ||
          (github.ref == 'refs/heads/main') && 'production' ||
          'development'
        }}
      # Add NVM setup commands as an environment variable to reuse
      NVM_SETUP: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm use 18 || nvm install 18
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js with NVM
        run: |
          ${{ env.NVM_SETUP }}
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"
      
      - name: Install dependencies
        run: |
          ${{ env.NVM_SETUP }}
          npm ci
      
      - name: Build for ${{ env.ENV_NAME }}
        run: |
          ${{ env.NVM_SETUP }}
          npm run build
      
      - name: Deploy to ${{ env.ENV_NAME }} server
        run: |
          echo "Deploying to ${{ env.ENV_NAME }} environment at ${{ env.DEPLOY_PATH }}"
          rm -rf ${{ env.DEPLOY_PATH }}*
          cp -r dist/* ${{ env.DEPLOY_PATH }}
          echo "Deployment complete!"