name: SolidJS Frontend Deployment

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  build-and-deploy:
    name: Build and Deploy SolidJS Frontend
    runs-on: self-hosted
    
    env:
      DEPLOY_PATH: ${{ github.ref == 'refs/heads/main' && '/var/www/ishan-garg.com/html/' || '/var/www/dev.ishan-garg.com/html/' }}
      ENV_NAME: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js with NVM
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 22 || nvm install 22  # Fallback to install if not available
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build for ${{ env.ENV_NAME }}
        run: npm run build
      
      - name: Deploy to ${{ env.ENV_NAME }} server
        run: |
          echo "Deploying to ${{ env.ENV_NAME }} environment at ${{ env.DEPLOY_PATH }}"
          rm -rf ${{ env.DEPLOY_PATH }}*
          cp -r dist/* ${{ env.DEPLOY_PATH }}
          echo "Deployment complete!"